bonus:
  cooldown-seconds: 10800

stars:
  offers:
    - stars: 5
      bonus: 100
    - stars: 10
      bonus: 250
    - stars: 20
      bonus: 600
    - stars: 50
      bonus: 2000

telegram:
  payment:
    provider-token: "ТВОЙ_PROVIDER_TOKEN_ОТ_PAYMENTS"

  bot:
    token: "8810189894:AAHcz7w0sYY04K_-ZfqHbqju5e4HB1ycZYg"
    username: "the_night_dream_bot"

minio:
  url: http://localhost:9000
  access-key: admin
  secret-key: password123
  bucket: porn-files

spring:
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
    deserialization:
      fail-on-unknown-properties: true
    property-naming-strategy: SNAKE_CASE

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/nightdreambot}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:buyfn2008}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false

server:
  port: 8080

admin:
  chat-id: 1210667437