package com.example.demo.state;

public enum AdminState {
    NONE,
    CREATING_PROMOCODE_WAITING_CODE,
    CREATING_PROMOCODE_WAITING_BONUS,
    CREATING_PROMOCODE_WAITING_EXPIRY,
    CREATING_PROMOCODE_WAITING_LIMIT,
    ADDING_BONUS_WAITING_USER,
    ADDING_BONUS_WAITING_AMOUNT
}